layout: default
name: Voron Documentation
description: Voron Official and Community Documentation
logo: "/images/voron_design_logo.png"
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
color_scheme: voron-dark
url: https://cluzl.github.io/isengajaa
search_enabled: true
search.button: true


